Add expected error checking

diff --git a/.github/workflows/test-local-action.yml b/.github/workflows/test-local-action.yml
--- a/.github/workflows/test-local-action.yml
+++ b/.github/workflows/test-local-action.yml
@@ -25,9 +25,31 @@ jobs:
         run: |
           echo "Todo: check the results of fake-output and fake-secret"
       
-      - name: Test output file
+      - name: Test output file and expected contents
+        shell: pwsh
         run: |
-          cat "actionlint-errors.json"       
+          $result = Get-Content "actionlint-errors.json"       
+          $items = @(ConvertFrom-Json $result -Depth 10)     
+      
+          $found1 = $false
+          foreach ($item in $items) { 
+            Write-Host "Found an error: "
+            Write-Host "Message:" $item.message
+            Write-Host "Filepath:" $item.filepath
+            Write-Host "Line:" $item.line
+
+            if ($item.filepath -eq ".github/workflows/test-local-action.yml" -and $item.line -eq 33) {
+              $found1 = $true
+            }
+          }      
+
+          if (!$found1){
+            echo "Error finding the first expected result. Exiting with failure"
+            exit 1
+          } 
+          else {
+            Write-Host "Found the expected error succesfully"
+          }
         
   job-with-errors:
     runs-on: ubuntu-latest
